spring.application.name=belaberung-backend
# MariaDB stuff
spring.datasource.url=${BELABERUNG_DB_URL:jdbc:mariadb://localhost:3306/chatapp?verifyServerCertificate=false&useSSL=false}
spring.datasource.username=${BELABERUNG_DB_USER:root}
spring.datasource.password=${BELABERUNG_DB_PASSWORD:root}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update